* Die Trying

You're not going to get rich, but you'll still die trying.

In this case there's not even the prospect of riches, this is only the source
of my madness -- my neverending quest for the best way to create a website,
under the pretense of a new website.

** Usage

Don't.

But if you must, honestly I'm not too sure how you'd use this. Myself, I open
sly and ~(ql:quickload:die-trying)~ and then ~(die-trying:start-dev)~ which
starts hunchentoot on port 4321 and starts a file watcher that will recompile
your HTML files whenever anything in ~www/~ changes.

I guess you can use this for your own project by doing the same as above and
either use ~www/~ for your source HTML files and ~out/~ for the output, or
update the values of ~*input-dir*~ and ~*output-dir~. I think that should be enough,
but tbh I've never tried.

To just output some files you can use ~die-trying:proces~ by itself to generate
your compiled HTML.

** Todo's [3/5]
- [X] Figure out some redneck ~<slot>~ system. (Not even redneck, just native
  slotting lol)
- [X] +Add a ~<lisp>~ element for running arbitrary lisp code, defined in HTML tags+
  (implemented via .lisp template files and parameterized .lisp fragments instead)
- [X] +Add tags for markup, such as ~<org-mode>~ and ~<markdown>,~ for rendering the
  inner text to the specified markup.+
- [ ] Add live-reload on the browser when files change in ~out/~
- [ ] Possibly add an API server to make this Fullstack™️
- [X] Figure out how to order element expansion to handle the case of nested elements
